### ISSUE TITLE
'Explore the supply chain' table

### ISSUE THREAD

**Issue by heatherknight08** [wikirate/transparency-tool#15]
Left align the factory list

Tweak the 'Sourcing from factories' block to navy #112053

<img width="347" alt="Screenshot 2020-06-23 at 09 16 14" src="https://user-images.githubusercontent.com/67009459/85378265-375c2780-b532-11ea-8b60-cc09c3cc3adc.png">

**Comment by aileenrob** [comment]
Hi Heather, this should be fixed now!

**Comment by ethn** [comment]
Now I'm confused.  That block is currently $navy: #1d1d2f, which seems to line up with the picture.

Is that correct, or do you want it to be $medium-blue: #112053?

(btw, it looks like several of the other "blue bugs" got started because I thought this meant I was supposed to change navy from 1d1d2f to 112053.  My bad!)

**Comment by heatherknight08** [comment]
Ah yes, you're right! Keep as $navy: #1d1d2f

**Comment by heatherknight08** [comment]
It was previously black I think, so looks perfect now

**Comment by ethn** [comment]
Thanks, Heather. Sorry for the confusion.
