### ISSUE TITLE
translated brand results

### ISSUE THREAD

**Issue by polyester** [wikirate/transparency-tool#21]
searching for a brand in a translated version, for instance https://fashionchecker.org/de takes you to the English brand result.
At the moment, that's fine, also because if you go manually to the translated brand result there are missing images and styling issues. Probably some parts of it need to be told to "do not translate this part"...

https://fashionchecker.org/de/brand-profile.html?q=170564 for example.

Translations are hard ;-) 
I'll try to dig a bit into the translation machinery, to see if I understand it and can be helpful here.

**Comment by ethn** [comment]
English remaining on the brand (on the German page linked to above)
- "Brands owned by":  easy, just missing translation in de.yml
- "Separate labor costs" : same
- "Living Wage Paid": same basically. (English in de.yml)
- text on A/B/C/D/E graphic -> this is on the image. We'd have to move to constructing this dynamically
- score descriptions -> this is coming from wikirate answers.  We'd have to start storing keys instead of the full text in those answers.  Probably involves reimporting.

**Comment by ethn** [comment]
ok to close?

**Comment by polyester** [comment]
Yep, OK to close.

**Comment by polyester** [comment]
reopening:
When you start from a translated version, for instance https://fashionchecker.org/fr and search for "adidas", it takes you to https://fashionchecker.org/brand-profile.html?q=7217 instead of https://fashionchecker.org/fr/brand-profile.html?q=7217

**Comment by ethn** [comment]
I made a quick change that makes things work on, eg `/de/` but not `/de`.  Will make that more robust...

**Comment by ethn** [comment]
Should be good now.
