### ISSUE TITLE
non-urgent: line breaks in homepage big statements

### ISSUE THREAD

**Issue by heatherknight08** [wikirate/transparency-tool#30]
This can be put at the bottom of your to-do list!
Could you put in some line breaks on the short statements on the homepage to match the original design?
<img width="375" alt="Screenshot 2020-06-25 at 19 38 39" src="https://user-images.githubusercontent.com/67009459/85779582-a779d180-b71b-11ea-91b1-9d01e3a95e59.png">

e.g.
LIVING
WAGES 
NOT 
POVERTY WAGES

Original design:
![HOME](https://user-images.githubusercontent.com/67009459/85780979-1c014000-b71d-11ea-8a2d-86665e6b54e1.jpg)

**Comment by aileenrob** [comment]
Thanks for flagging! Have added to Ethan's list - should be a quick fix

**Comment by ethn** [comment]
It's not actually quite as straightforward as you might think.

If we were only working in English, it would be trivial. But since we're dealing with translations, and there's no HTML in the translation files, we can't just plop in HTML fixes.

What we can do:

1. Use CSS to make it so that some styling decisions hold across languages.  Eg, if you refresh staging, you'll see I made "living wages not poverty wages" tall and thin, so it looks just like the mockup without having to make any HTML changes. Where we can do this, we should, but it won't always work, as in the case of the more nuanced line breaks in the top section.

2. break the phrases into separate translatable bits.  In general, I think we should NOT do this, as it will often be confusing for the translators and may force stylistic restraints that don't work well across languages.

3. make it so those headers turn white space line breaks in the translation file into HTML line breaks. I like this last solution and will add it when I can. This will give translators nuanced control should they choose to use it.

**Comment by heatherknight08** [comment]
Ah I see. Happy to go with your recommendations and not to worry about it for translations!

**Comment by ethn** [comment]
OK, I think we're in good shape in English on most of the site now.  Do you see any more line break issues?

**Comment by heatherknight08** [comment]
Ooh could you fix this on one the About page?

![Uploading Screenshot 2020-06-26 at 18.07.15.png…]()

Should be:
<img width="303" alt="Screenshot 2020-06-26 at 18 08 08" src="https://user-images.githubusercontent.com/67009459/85882893-00a73b00-b7d8-11ea-8b64-7362efb8d044.png">

And this one:

<img width="384" alt="Screenshot 2020-06-26 at 18 08 24" src="https://user-images.githubusercontent.com/67009459/85882921-0ac93980-b7d8-11ea-9ef2-bd57689ab828.png">

To this:
<img width="205" alt="Screenshot 2020-06-26 at 18 08 45" src="https://user-images.githubusercontent.com/67009459/85882944-1452a180-b7d8-11ea-97dc-398f50735fa3.png">

**Comment by ethn** [comment]
I think these are all fixed (and live) now. Ok to close?

**Comment by heatherknight08** [comment]
Good to close!
